package cn.psl.hy.blog.mapper;

import cn.psl.hy.blog.model.TBlogType;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TBlogTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_type
     *
     * @mbg.generated
     */
    int insert(TBlogType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_type
     *
     * @mbg.generated
     */
    TBlogType selectByPrimaryKey(String typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_type
     *
     * @mbg.generated
     */
    List<TBlogType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TBlogType record);
}