package cn.psl.hy.blog.mapper;

import cn.psl.hy.blog.model.TBlogUser;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TBlogUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_user
     *
     * @mbg.generated
     */
    int insert(TBlogUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_user
     *
     * @mbg.generated
     */
    List<TBlogUser> selectAll();
    /**
     * 检查用户输入的用户名和密码是否正确
     */ 
    public TBlogUser checkUser (String userName, String password);
}