# 服务端
server:
  port: 8082
  servlet:
    session:
      timeout: 10
  tomcat:
    uri-encoding: UTF-8      
# 数据库接连
spring:
  # 配置视图解析器
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  # 配置数据源
  datasource:
    # 数据库基础配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 1
    # 属性配置
    initial-size: 5
    max-idle: 10
    max-wait: 10000
    min-idle: 5
# mybatis配置
mybatis:
  mapper-locations: classpath:cn/psl/hy/blog/mapper/*.xml
# 定时任务配置
timers:
  cron: 0 12 15 * * ?
# 分页管理
pagehelper:
  offset-as-page-num: true
  row-bounds-with-count: true
  reasonable: true
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql